language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

services:
  - mysql
  - postgresql

script:
    - vendor/bin/tester tests -s -p php -c tests/php.ini-travis

after_failure:
    # Print *.actual content
    - for i in `find tests -name \*.actual -o -name \*.expected`; do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Update composer
    - composer self-update
    
    # Install Nette Tester
    - travis_retry composer update --no-interaction --prefer-dist

    # Create databases.ini
    - cp ./tests/databases.sample.ini ./tests/databases.ini

    # Create databases
    - psql -c 'CREATE DATABASE metistest;' -U postgres
    - mysql -e 'CREATE DATABASE metistest;'
  
sudo: false
